

#ifndef TORCHFOLD_SRC_TORCHFOLD_PARSERS_PYTHON_FASTA_ITERATOR_PYBIND_H_
#define TORCHFOLD_SRC_TORCHFOLD_PARSERS_PYTHON_FASTA_ITERATOR_PYBIND_H_

#include "pybind11/pybind11.h"

namespace torchx {

void RegisterModuleFastaIterator(pybind11::module m);

}

#endif  // TORCHFOLD_SRC_TORCHFOLD_PARSERS_PYTHON_FASTA_ITERATOR_PYBIND_H_
