#ifndef TORCHFOLD_SRC_TORCHFOLD_STRUCTURE_PYTHON_MMCIF_UTILS_PYBIND_H_
#define TORCHFOLD_SRC_TORCHFOLD_STRUCTURE_PYTHON_MMCIF_UTILS_PYBIND_H_

#include "pybind11/pybind11.h"

namespace torchfold {

void RegisterModuleMmcifUtils(pybind11::module m);

}

#endif  // TORCHFOLD_SRC_TORCHFOLD_STRUCTURE_PYTHON_MMCIF_UTILS_PYBIND_H_
